pipeline {
    agent any
    //tools {
    //gradle 'gradle-7.3'
      //     } //tools
    stages {
        stage('Compile Stage') {
            steps {
                  echo 'executing compile stage....'
               // sh './gradlew -v'
                    } //steps
                   }// stage

        stage('Test') {
            steps {
                echo 'Testing.ffff..gg.'
                   }
                      }
        stage('Deploy') {
            steps {
                echo 'Deploying.......'
            }
        }

        }// stages
    } //pipeline
