pipeline{
agent any {
stages {
stage ('Compile'){
steps {
 echo 'compiling application'
}
}
// Test
stage ('Test'){
steps {
 echo 'Testing application'
}
}
// Deploy
stage ('Deploy'){
steps {
 echo 'Deploying application'
}
}
}

}

}